### ISSUE TITLE
Housekeeping Checklist

### ISSUE THREAD

**Issue by kevinren1108** [kevinren1108/Apollo-Capstone-Project#46]
Ezparking Client
- [x] Connect to API
- [x] Load destination
- [x] Load parking lot
- [x] Generate navigation link
- [x] Calculate walk and run time

Ezparking Myadmin
- [x] Change code to work with new update API
- [x] Change code to work with new delete API
- [x] Fix instruction section gap issue in different screen ratio

Ezparking Backend
- [x] Separate type column
- [x] Get parking lot API for a selected destination(need to return a ranked parking lot)
- [x] Get all destination API 
- [x] Increase/decrease vehicle count API for specific parking lot
- [x] https://github.com/kevinren1108/Apollo-Capstone-Project/issues/43
- [x] API document
- [x] Cookie valid time
- [x] API call authorization
- [x] Redis data sync with the database

| API endpoint       | request  | respond body      | respond code|Explanation|
|--------------------|----------|-------------------|--------------------|--------|
| /getDestination | GET     | None  | 200|Return a Json with all destination|
| /getParkinglot| GET     |{destination: XXX}| 200|Return a Json with first five available parking lot and travel distance |
| /updatePLwp  | POST|None | 200|Update parking lot waypoint, detail refer to issue 43|
| /updateDNwp | POST| None   | 200|Update destination waypoint, detail refer to issue 43|

Ezparking AI
- [x] Fix call API will cause processing purse issue
- [x] Add parameter when starting the AI to work with new increase/decrease API

**Comment by kevinren1108** [comment]
For Ezparking AI
I fixed those two issues:
1. Fix call API will cause processing purse issue
2. Add a parameter when starting the AI to work with new increase/decrease API
Check the detail on pull request #47

**Comment by kevinren1108** [comment]
Ezparking Myadmin
I fixed an issue and change the code to use the new API for update and delete waypoints
1.  Change code to work with new update API
2.  Change code to work with new delete API
3.  Fix the instruction section gap issue in different screen ratio

Check the detail on the pull request #48
